{{- range $serviceName, $serviceConfig := .Values.services }}
{{- if and $serviceConfig.enabled $serviceConfig.configMap.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $serviceName }}-config
  labels:
    app: {{ $serviceName }}
    {{- include "assetcore.labels" $ | nindent 4 }}
data:
  {{- range $key, $value := $serviceConfig.configMap.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
{{- end }}