{{- range $serviceName, $serviceConfig := .Values.services }}
{{- if $serviceConfig.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $serviceName }}-svc
  labels:
    app: {{ $serviceName }}
    {{- include "assetcore.labels" $ | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ $serviceConfig.servicePort | default 80 }}
      targetPort: {{ $serviceConfig.containerPort | default 8080 }}
      protocol: TCP
  selector:
    app: {{ $serviceName }}
{{- end }}
{{- end }}